kyverno/kyverno-envoy-plugin

.github/workflows/check-actions.yaml, .github/workflows/semantics-pr.yaml
=> chore: add ci jobs

README.md
=> chore: add a placeholder readme

README.md
Closes: #1 
Open a issue to add ROADMAP.md .
=> chore: add a README

install-istio.sh
=> feat: script to install Istio on Kind

demo/istio/bootstrap.sh, demo/istio/manifests/echo-service.yaml
=> fix: istio demo kind cluster

demo/istio/README.md
If current sequence not worked 
Then try below sequence 
1) ./bootstrap.sh
2) deploy sample-application 
3) deploy Authorization Server 
4) Registor authorization provider 
5) deploy istio AuthorizationPolicy 
6) then test with this command `kubectl run test -it --rm --restart=Never --image=busybox -- wget -q --header="x-ext-authz: allow" --output-document - echo.demo.svc.cluster.local:8080/foo`  
I have tried both sequence i got sometimes negetive result and positive results according to what is was expected .
=> chore: added all TODOs

.gitignore, Makefile
=> chore: install ko

.github/workflows/tests.yaml, Makefile
=> chore: add tests workflow

main.go
```
sanskar@sanskar-HP-Laptop-15s-du1xxx:~/kyverno-envoy-plugin$ go run main.go 
Starting HTTP server on Port 8080
Starting GRPC server on Port 9090
```
=> perf: added http and grpc server in diff goroutines

go.mod, go.sum, main.go
=> fix: improve signals

.github/workflows/tests.yaml, Makefile, tests/e2e-test/chainsaw-test.yaml, tests/e2e-test/deployment.yaml
Added end to end test case for kyverno-envoy-plugin
Used kyverno/chainsaw to make CI integrated end to end test .
=> ci: add end to end test case for kyverno-envoy-plugin

.gitignore, Makefile, main.go
=> fix: commands in main

pkg/commands/serve/command.go, pkg/server/handlers/health.go, pkg/server/server.go, pkg/signals/context.go
=> refactor: health handler

.github/workflows/codeql.yaml
=> chore: add codeql workflow

.github/dependabot.yml, .github/workflows/check-actions.yaml, .github/workflows/codeql.yaml, .github/workflows/docs-main.yaml, .github/workflows/docs-release.yaml, .github/workflows/ko-publish.yaml, .github/workflows/lint.yaml, .github/workflows/semantics-pr.yaml, Makefile
=> feat: add ko-publish

.github/workflows/ko-publish.yaml
=> fix: ko publish

.vscode/launch.json
=> chore: add vscode file

.github/dependabot.yml, .github/workflows/check-actions.yaml, .github/workflows/codeql.yaml, .github/workflows/docs-main.yaml, .github/workflows/docs-release.yaml, .github/workflows/ko-publish.yaml, .github/workflows/lint.yaml, .github/workflows/semantics-pr.yaml, .github/workflows/tests.yaml
=> chore: bump chainsaw

.github/workflows/ko-publish.yaml, .github/workflows/tests.yaml, Makefile, main.go
=> refactor: makefile targets

.github/workflows/release.yaml, .goreleaser.yaml
Add goreleaser config.
Fixes https://github.com/kyverno/kyverno-envoy-plugin/issues/133
=> feat: add goreleaser config

pkg/commands/inject/command.go, pkg/server/run.go, pkg/signals/context.go, pkg/signals/context_test.go
=> feat: factorise server run code

.github/workflows/codeql.yaml, .github/workflows/ko-publish.yaml, .github/workflows/lint.yaml, .github/workflows/release.yaml, .github/workflows/semantics-pr.yaml, .github/workflows/tests.yaml, Makefile
Prepare images for chainsaw tests.
=> chore: prepare images for chainsaw tests

docs/RELEASE.md
=> docs: add release docs

.github/ISSUE_TEMPLATE/config.yml
=> chore: add issues config

.github/workflows/helm-release.yaml
=> feat: add chart release workflow

.github/workflows/helm-release.yaml, charts/kyverno-authz-server/templates/_helpers.tpl, charts/kyverno-authz-server/templates/deployment.yaml
=> fix: set charts app version

.schemas/json/authorizationpolicy-envoy-v1alpha1.json, Makefile
=> chore: bump kind node

go.mod, go.sum, pkg/policy/provider.go
=> feat: add policy controller

website/docs/overrides/home.html, website/docs/quick-start/index.md, website/docs/quick-start/install.md, website/docs/quick-start/next-steps.md, website/mkdocs.yaml
=> docs: add quick start section

website/docs/cel-extensions/envoy.md, website/docs/cel-extensions/index.md, website/docs/cel-extensions/jwt.md, website/mkdocs.yaml
=> docs: add cel libs documentation

website/docs/cel-extensions/envoy.md
=> docs: add envoy lib examples

website/docs/performance/index.md, website/mkdocs.yaml
=> docs: performance section

website/docs/cel-extensions/envoy.md, website/docs/cel-extensions/jwt.md
=> docs: CEL libs types

website/docs/tutorials/istio/index.md
=> docs: typo

website/mkdocs.base.yaml
=> docs: fix site url

.vscode/launch.json, charts/kyverno-authz-server/README.md, charts/kyverno-authz-server/values.yaml, charts/kyverno-sidecar-injector/README.md, charts/kyverno-sidecar-injector/values.yaml, pkg/commands/root/command.go, pkg/commands/serve/authz-server/command.go, pkg/commands/serve/command.go, pkg/commands/serve/sidecar-injector/command.go, pkg/sidecar/sidecar.go
Refactor server commands names.
=> refactor: server commands names

pkg/authz/cel/libs/envoy/impl.go, pkg/authz/cel/libs/envoy/lib.go, website/docs/cel-extensions/envoy.md
Add query param envoy helpers.
=> feat: add query param envoy helpers

website/docs/policies/authorization-rules.md
=> docs: small fix

.github/workflows/tests.yaml, apis/v1alpha1/types_test.go
=> chore: add unit tests

.manifests/policies/demo-policy.example.com.yaml, ROADMAP.md
=> chore: add road map

website/docs/tutorials/envoy-gateway/index.md, website/docs/tutorials/istio/index.md, website/mkdocs.yaml
=> docs: add envoy gateway tutorial

.crds/envoy.kyverno.io_authorizationpolicies.yaml, .github/workflows/tests.yaml, Makefile, charts/kyverno-authz-server/templates/crds.yaml, tests/e2e/authz-server/allow/chainsaw-test.yaml, tests/e2e/authz-server/allow/istio-policy.yaml, tests/e2e/authz-server/allow/policy.yaml, tests/e2e/authz-server/allow/shell.yaml, tests/e2e/authz-server/default/chainsaw-test.yaml, tests/e2e/authz-server/default/istio-policy.yaml, tests/e2e/authz-server/default/policy.yaml, tests/e2e/authz-server/default/shell.yaml, tests/e2e/authz-server/deny/chainsaw-test.yaml, tests/e2e/authz-server/deny/istio-policy.yaml, tests/e2e/authz-server/deny/policy.yaml, tests/e2e/authz-server/deny/shell.yaml
=> chore: add istio in e2e tests

README.md
Fix bad link in readme.
Fixes #281
=> fix: bad link in readme

ROADMAP.md
=> chore: update roadmap

.crds/envoy.kyverno.io_authorizationpolicies.yaml, charts/kyverno-authz-server/templates/crds.yaml
=> fix: update codegen

pkg/authz/cel/libs/jwt/impl.go
=> refactor: use utils in jwt lib

.github/workflows/lint.yaml, pkg/policy/provider.go, pkg/server/handlers/admission.go
=> chore: bump linter

.github/workflows/tests.yaml, Makefile
Make kyverno authz service configurable.
=> chore: make kyverno authz service configurable

website/docs/tutorials/kgateway/index.md
Add kgateway tutorial (part 1).
=> docs: add kgateway tutorial (part 1)

website/docs/tutorials/kgateway/index.md
Add kgateway tutorial (part 2).
=> docs: add kgateway tutorial (part 2)

pkg/commands/serve/authz-server/command.go
=> feat: add external sources flag

.github/workflows/tests.yaml
=> chore: add missing required jobs

.github/workflows/pr.yaml, charts/kyverno-sidecar-injector/README.md, charts/kyverno-sidecar-injector/templates/deployment.yaml, charts/kyverno-sidecar-injector/values.yaml, pkg/commands/serve/sidecar-injector/command.go, pkg/sidecar/sidecar.go, pkg/webhook/mutation/sidecar-injector.go
Pass external policy sources to sidecar injector.
=> feat: pass external policy sources to sidecar injector

.crds/envoy.kyverno.io_authorizationpolicies.yaml, .crds/envoy.kyverno.io_validatingpolicies.yaml, charts/kyverno-authz-server/templates/crds.yaml, charts/kyverno-sidecar-injector/templates/crds.yaml, pkg/data/crds/envoy.kyverno.io_authorizationpolicies.yaml, pkg/data/crds/envoy.kyverno.io_validatingpolicies.yaml
=> fix: codegen

go.mod, go.sum, pkg/engine/apol/compiler/policy.go, pkg/engine/variables/imagedata.go, pkg/engine/vpol/compiler/policy.go
=> feat: register kyverno CEL data

pkg/commands/serve/authz-server/command.go, pkg/commands/serve/validation-webhook/command.go
Use field selector in watcher.
=> feat: use field selector in watcher

.crds/envoy.kyverno.io_authorizationpolicies.yaml, apis/v1alpha1/types.go, apis/v1alpha1/validating_policy.go, charts/kyverno-authz-server/templates/crds.yaml, charts/kyverno-sidecar-injector/templates/crds.yaml, pkg/data/crds/envoy.kyverno.io_authorizationpolicies.yaml
=> fix: add apol short name

pkg/commands/serve/validation-webhook/command.go
Remove cache usage from validation webhook.
=> fix: remove cache usage from validation webhook

pkg/engine/apol/provider/provider.go, pkg/engine/vpol/provider/provider.go, pkg/utils/map.go
=> refactor: factorize ToSortedSlice

main.go, pkg/authz/service.go, pkg/commands/serve/validation-webhook/command.go, pkg/engine/apol/provider/provider.go, pkg/engine/vpol/provider/provider.go, pkg/server/grpc.go, pkg/server/http.go
Use controller-runtime logger.
=> fix: use controller-runtime logger

.schemas/json/authorizationpolicy-envoy-v1alpha1.json, Makefile
Bump default kind node to 1.34.
=> chore: bump default kind node to 1.34

website/mkdocs.yaml
=> docs: move reference tab

website/docs/quick-start/authz-server.md, website/docs/quick-start/sidecar-injector.md
Add sidecar injector quick start.
=> docs: add sidecar injector quick start

website/docs/policies/apol/authorization-rules.md, website/docs/policies/apol/index.md, website/docs/policies/index.md, website/docs/policies/vpol/index.md, website/docs/policies/vpol/validation-rules.md, website/mkdocs.yaml
=> docs: add validating policy docs

website/mkdocs.yaml
Add external policy sources to the nav.
=> docs: add external policy sources to the nav

pkg/cel/libs/jwt/impl.go
=> fix: audience decoding

website/docs/tutorials/istio/index.md
Remove the need for istioctl (part 2).
=> docs: remove the need for istioctl (part 2)
